// swift-tools-version:5.9
// Smoke test for the BoltFFI Swift binding. Run via tests/bindings/run.sh swift (macOS only).
import PackageDescription

let package = Package(
    name: "EngineBindingsTest",
    platforms: [.macOS(.v13)],
    dependencies: [
        // generated by `boltffi pack apple` into crates/engine/dist/apple
        .package(path: "../../../dist/apple"),
    ],
    targets: [
        .testTarget(
            name: "VersionTests",
            dependencies: [.product(name: "QuranMuaalemEngine", package: "apple")]
        ),
    ]
)
